name: Artem Grinn 
description: "JavaScript, TypeScript and C# Developer"
meta_description: "Blogging about web development: JavaScript, TypeScript, ReactJS, Webpack, C#, ASP.NET MVC"

aboutPage: true
markdown: kramdown
highlighter: rouge

paginate: 20
baseurl: /
domain_name: 'http://agrinn.ru'
google_analytics: 'UA-88958543-1'
disqus: true
disqus_shortname: 'agrinn-ru'

# Details for the RSS feed generator
url:            'http://agrinn.ru'
author:         'Artem Grinn'
authorTwitter:  'grinn57'

permalink:       /blog/:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
