# Site settings
title: Pages
email: grinn.art@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/pages/" # the subpath of your site, e.g. /blog/
url: "http://agrinn.ru" # the base hostname & protocol for your site
twitter_username: a.grinn
github_username:  ArtemGrinn

# Build settings
markdown: kramdown
